// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AuthAccountHandle : RemoteTableHandle<EventContext, AuthAccount>
        {
            protected override string RemoteTableName => "auth_account";

            public sealed class AccountIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(AuthAccount row) => row.AccountId;

                public AccountIdUniqueIndex(AuthAccountHandle table) : base(table) { }
            }

            public readonly AccountIdUniqueIndex AccountId;

            public sealed class CurrentIdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(AuthAccount row) => row.CurrentIdentity;

                public CurrentIdentityIndex(AuthAccountHandle table) : base(table) { }
            }

            public readonly CurrentIdentityIndex CurrentIdentity;

            public sealed class UsernameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(AuthAccount row) => row.Username;

                public UsernameUniqueIndex(AuthAccountHandle table) : base(table) { }
            }

            public readonly UsernameUniqueIndex Username;

            internal AuthAccountHandle(DbConnection conn) : base(conn)
            {
                AccountId = new(this);
                CurrentIdentity = new(this);
                Username = new(this);
            }

            protected override object GetPrimaryKey(AuthAccount row) => row.AccountId;
        }

        public readonly AuthAccountHandle AuthAccount;
    }
}
