// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CardTypeWeightHandle : RemoteTableHandle<EventContext, CardTypeWeight>
        {
            protected override string RemoteTableName => "card_type_weight";

            public sealed class InstanceIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(CardTypeWeight row) => row.InstanceId;

                public InstanceIdUniqueIndex(CardTypeWeightHandle table) : base(table) { }
            }

            public readonly InstanceIdUniqueIndex InstanceId;

            internal CardTypeWeightHandle(DbConnection conn) : base(conn)
            {
                InstanceId = new(this);
            }

            protected override object GetPrimaryKey(CardTypeWeight row) => row.InstanceId;
        }

        public readonly CardTypeWeightHandle CardTypeWeight;
    }
}
