// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CardFactionWeightHandle : RemoteTableHandle<EventContext, CardFactionWeight>
        {
            protected override string RemoteTableName => "card_faction_weight";

            public sealed class InstanceIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(CardFactionWeight row) => row.InstanceId;

                public InstanceIdUniqueIndex(CardFactionWeightHandle table) : base(table) { }
            }

            public readonly InstanceIdUniqueIndex InstanceId;

            internal CardFactionWeightHandle(DbConnection conn) : base(conn)
            {
                InstanceId = new(this);
            }

            protected override object GetPrimaryKey(CardFactionWeight row) => row.InstanceId;
        }

        public readonly CardFactionWeightHandle CardFactionWeight;
    }
}
