// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CardLevelWeightHandle : RemoteTableHandle<EventContext, CardLevelWeight>
        {
            protected override string RemoteTableName => "card_level_weight";

            public sealed class InstanceIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(CardLevelWeight row) => row.InstanceId;

                public InstanceIdUniqueIndex(CardLevelWeightHandle table) : base(table) { }
            }

            public readonly InstanceIdUniqueIndex InstanceId;

            internal CardLevelWeightHandle(DbConnection conn) : base(conn)
            {
                InstanceId = new(this);
            }

            protected override object GetPrimaryKey(CardLevelWeight row) => row.InstanceId;
        }

        public readonly CardLevelWeightHandle CardLevelWeight;
    }
}
