// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CConnectionHandle : RemoteTableHandle<EventContext, Connection>
        {
            protected override string RemoteTableName => "c_connection";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Connection row) => row.Identity;

                public IdentityUniqueIndex(CConnectionHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal CConnectionHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(Connection row) => row.Identity;
        }

        public readonly CConnectionHandle CConnection;
    }
}
