// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DataSignatureHandle : RemoteTableHandle<EventContext, DataSignature>
        {
            protected override string RemoteTableName => "data_signature";

            public sealed class ValidateInfoIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(DataSignature row) => row.ValidateInfoId;

                public ValidateInfoIdUniqueIndex(DataSignatureHandle table) : base(table) { }
            }

            public readonly ValidateInfoIdUniqueIndex ValidateInfoId;

            internal DataSignatureHandle(DbConnection conn) : base(conn)
            {
                ValidateInfoId = new(this);
            }

            protected override object GetPrimaryKey(DataSignature row) => row.ValidateInfoId;
        }

        public readonly DataSignatureHandle DataSignature;
    }
}
