// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class HeroCardHandle : RemoteTableHandle<EventContext, HeroCard>
        {
            protected override string RemoteTableName => "hero_card";

            public sealed class CardNameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(HeroCard row) => row.CardName;

                public CardNameUniqueIndex(HeroCardHandle table) : base(table) { }
            }

            public readonly CardNameUniqueIndex CardName;

            public sealed class HeroCardIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(HeroCard row) => row.HeroCardId;

                public HeroCardIdUniqueIndex(HeroCardHandle table) : base(table) { }
            }

            public readonly HeroCardIdUniqueIndex HeroCardId;

            internal HeroCardHandle(DbConnection conn) : base(conn)
            {
                CardName = new(this);
                HeroCardId = new(this);
            }

            protected override object GetPrimaryKey(HeroCard row) => row.HeroCardId;
        }

        public readonly HeroCardHandle HeroCard;
    }
}
