// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MatchQueueHandle : RemoteTableHandle<EventContext, MatchQueue>
        {
            protected override string RemoteTableName => "match_queue";

            public sealed class UsernameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(MatchQueue row) => row.Username;

                public UsernameUniqueIndex(MatchQueueHandle table) : base(table) { }
            }

            public readonly UsernameUniqueIndex Username;

            internal MatchQueueHandle(DbConnection conn) : base(conn)
            {
                Username = new(this);
            }

            protected override object GetPrimaryKey(MatchQueue row) => row.Username;
        }

        public readonly MatchQueueHandle MatchQueue;
    }
}
