// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MatchContextHandle : RemoteTableHandle<EventContext, MatchContext>
        {
            protected override string RemoteTableName => "match_context";

            public sealed class MatchIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(MatchContext row) => row.MatchId;

                public MatchIdUniqueIndex(MatchContextHandle table) : base(table) { }
            }

            public readonly MatchIdUniqueIndex MatchId;

            internal MatchContextHandle(DbConnection conn) : base(conn)
            {
                MatchId = new(this);
            }

            protected override object GetPrimaryKey(MatchContext row) => row.MatchId;
        }

        public readonly MatchContextHandle MatchContext;
    }
}
