// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerAccountHandle : RemoteTableHandle<EventContext, PlayerAccount>
        {
            protected override string RemoteTableName => "player_account";

            public sealed class UsernameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(PlayerAccount row) => row.Username;

                public UsernameUniqueIndex(PlayerAccountHandle table) : base(table) { }
            }

            public readonly UsernameUniqueIndex Username;

            internal PlayerAccountHandle(DbConnection conn) : base(conn)
            {
                Username = new(this);
            }

            protected override object GetPrimaryKey(PlayerAccount row) => row.Username;
        }

        public readonly PlayerAccountHandle PlayerAccount;
    }
}
