// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerContextHandle : RemoteTableHandle<EventContext, PlayerContext>
        {
            protected override string RemoteTableName => "player_context";

            public sealed class MatchIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(PlayerContext row) => row.MatchId;

                public MatchIdIndex(PlayerContextHandle table) : base(table) { }
            }

            public readonly MatchIdIndex MatchId;

            public sealed class UsernameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(PlayerContext row) => row.Username;

                public UsernameUniqueIndex(PlayerContextHandle table) : base(table) { }
            }

            public readonly UsernameUniqueIndex Username;

            internal PlayerContextHandle(DbConnection conn) : base(conn)
            {
                MatchId = new(this);
                Username = new(this);
            }

            protected override object GetPrimaryKey(PlayerContext row) => row.Username;
        }

        public readonly PlayerContextHandle PlayerContext;
    }
}
