// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerBaseHandHandle : RemoteTableHandle<EventContext, PlayerBaseCardHand>
        {
            protected override string RemoteTableName => "player_base_hand";

            public sealed class BaseCardIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(PlayerBaseCardHand row) => row.BaseCardId;

                public BaseCardIdIndex(PlayerBaseHandHandle table) : base(table) { }
            }

            public readonly BaseCardIdIndex BaseCardId;

            public sealed class CardInstanceIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(PlayerBaseCardHand row) => row.CardInstanceId;

                public CardInstanceIdUniqueIndex(PlayerBaseHandHandle table) : base(table) { }
            }

            public readonly CardInstanceIdUniqueIndex CardInstanceId;

            public sealed class MatchIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(PlayerBaseCardHand row) => row.MatchId;

                public MatchIdIndex(PlayerBaseHandHandle table) : base(table) { }
            }

            public readonly MatchIdIndex MatchId;

            public sealed class OwnerIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(PlayerBaseCardHand row) => row.Owner;

                public OwnerIndex(PlayerBaseHandHandle table) : base(table) { }
            }

            public readonly OwnerIndex Owner;

            internal PlayerBaseHandHandle(DbConnection conn) : base(conn)
            {
                BaseCardId = new(this);
                CardInstanceId = new(this);
                MatchId = new(this);
                Owner = new(this);
            }

            protected override object GetPrimaryKey(PlayerBaseCardHand row) => row.CardInstanceId;
        }

        public readonly PlayerBaseHandHandle PlayerBaseHand;
    }
}
