// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerTimerScheduleHandle : RemoteTableHandle<EventContext, PlayerTimerSchedule>
        {
            protected override string RemoteTableName => "player_timer_schedule";

            public sealed class IdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerTimerSchedule row) => row.Id;

                public IdUniqueIndex(PlayerTimerScheduleHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class UsernameIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(PlayerTimerSchedule row) => row.Username;

                public UsernameIndex(PlayerTimerScheduleHandle table) : base(table) { }
            }

            public readonly UsernameIndex Username;

            internal PlayerTimerScheduleHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                Username = new(this);
            }

            protected override object GetPrimaryKey(PlayerTimerSchedule row) => row.Id;
        }

        public readonly PlayerTimerScheduleHandle PlayerTimerSchedule;
    }
}
