// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UserProfileHandle : RemoteTableHandle<EventContext, UserProfile>
        {
            protected override string RemoteTableName => "user_profile";

            public sealed class AccountIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(UserProfile row) => row.AccountId;

                public AccountIdUniqueIndex(UserProfileHandle table) : base(table) { }
            }

            public readonly AccountIdUniqueIndex AccountId;

            internal UserProfileHandle(DbConnection conn) : base(conn)
            {
                AccountId = new(this);
            }

            protected override object GetPrimaryKey(UserProfile row) => row.AccountId;
        }

        public readonly UserProfileHandle UserProfile;
    }
}
