// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ValidateInfoHandle : RemoteTableHandle<EventContext, ValidateInfo>
        {
            protected override string RemoteTableName => "validate_info";

            public sealed class ValidateInfoIdUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(ValidateInfo row) => row.ValidateInfoId;

                public ValidateInfoIdUniqueIndex(ValidateInfoHandle table) : base(table) { }
            }

            public readonly ValidateInfoIdUniqueIndex ValidateInfoId;

            internal ValidateInfoHandle(DbConnection conn) : base(conn)
            {
                ValidateInfoId = new(this);
            }

            protected override object GetPrimaryKey(ValidateInfo row) => row.ValidateInfoId;
        }

        public readonly ValidateInfoHandle ValidateInfo;
    }
}
