// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AuthAccount
    {
        [DataMember(Name = "AccountId")]
        public uint AccountId;
        [DataMember(Name = "Username")]
        public string Username;
        [DataMember(Name = "Password")]
        public string Password;
        [DataMember(Name = "IsOnline")]
        public bool IsOnline;
        [DataMember(Name = "CreatedAt")]
        public SpacetimeDB.Timestamp CreatedAt;
        [DataMember(Name = "CurrentIdentity")]
        public SpacetimeDB.Identity CurrentIdentity;

        public AuthAccount(
            uint AccountId,
            string Username,
            string Password,
            bool IsOnline,
            SpacetimeDB.Timestamp CreatedAt,
            SpacetimeDB.Identity CurrentIdentity
        )
        {
            this.AccountId = AccountId;
            this.Username = Username;
            this.Password = Password;
            this.IsOnline = IsOnline;
            this.CreatedAt = CreatedAt;
            this.CurrentIdentity = CurrentIdentity;
        }

        public AuthAccount()
        {
            this.Username = "";
            this.Password = "";
        }
    }
}
