// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BaseCard
    {
        [DataMember(Name = "BaseCardId")]
        public uint BaseCardId;
        [DataMember(Name = "CardLevel")]
        public uint CardLevel;
        [DataMember(Name = "CardType")]
        public CardType CardType;
        [DataMember(Name = "CardFaction")]
        public CardFaction CardFaction;
        [DataMember(Name = "CardDescription")]
        public string CardDescription;

        public BaseCard(
            uint BaseCardId,
            uint CardLevel,
            CardType CardType,
            CardFaction CardFaction,
            string CardDescription
        )
        {
            this.BaseCardId = BaseCardId;
            this.CardLevel = CardLevel;
            this.CardType = CardType;
            this.CardFaction = CardFaction;
            this.CardDescription = CardDescription;
        }

        public BaseCard()
        {
            this.CardDescription = "";
        }
    }
}
