// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CardFactionWeight
    {
        [DataMember(Name = "InstanceId")]
        public string InstanceId;
        [DataMember(Name = "Weight")]
        public float Weight;

        public CardFactionWeight(
            string InstanceId,
            float Weight
        )
        {
            this.InstanceId = InstanceId;
            this.Weight = Weight;
        }

        public CardFactionWeight()
        {
            this.InstanceId = "";
        }
    }
}
