// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Connection
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "IsConnected")]
        public bool IsConnected;
        [DataMember(Name = "IsValidated")]
        public bool IsValidated;

        public Connection(
            SpacetimeDB.Identity Identity,
            bool IsConnected,
            bool IsValidated
        )
        {
            this.Identity = Identity;
            this.IsConnected = IsConnected;
            this.IsValidated = IsValidated;
        }

        public Connection()
        {
        }
    }
}
