// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DataSignature
    {
        [DataMember(Name = "ValidateInfoId")]
        public string ValidateInfoId;
        [DataMember(Name = "PlayLoad")]
        public string PlayLoad;

        public DataSignature(
            string ValidateInfoId,
            string PlayLoad
        )
        {
            this.ValidateInfoId = ValidateInfoId;
            this.PlayLoad = PlayLoad;
        }

        public DataSignature()
        {
            this.ValidateInfoId = "";
            this.PlayLoad = "";
        }
    }
}
