// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HeroCard
    {
        [DataMember(Name = "HeroCardId")]
        public uint HeroCardId;
        [DataMember(Name = "CardName")]
        public string CardName;
        [DataMember(Name = "CardDescription")]
        public string CardDescription;

        public HeroCard(
            uint HeroCardId,
            string CardName,
            string CardDescription
        )
        {
            this.HeroCardId = HeroCardId;
            this.CardName = CardName;
            this.CardDescription = CardDescription;
        }

        public HeroCard()
        {
            this.CardName = "";
            this.CardDescription = "";
        }
    }
}
