// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class HeroCard
    {
        [DataMember(Name = "HeroCardId")]
        public uint HeroCardId;
        [DataMember(Name = "CardName")]
        public string CardName;
        [DataMember(Name = "CardDescription")]
        public string CardDescription;
        [DataMember(Name = "Stats")]
        public StatsUnion Stats;

        public HeroCard(
            uint HeroCardId,
            string CardName,
            string CardDescription,
            StatsUnion Stats
        )
        {
            this.HeroCardId = HeroCardId;
            this.CardName = CardName;
            this.CardDescription = CardDescription;
            this.Stats = Stats;
        }

        public HeroCard()
        {
            this.CardName = "";
            this.CardDescription = "";
            this.Stats = null!;
        }
    }
}
