// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MatchQueue
    {
        [DataMember(Name = "Username")]
        public string Username;
        [DataMember(Name = "JoinTime")]
        public SpacetimeDB.Timestamp JoinTime;
        [DataMember(Name = "Evaluate")]
        public uint Evaluate;
        [DataMember(Name = "TargetPlayerCount")]
        public uint TargetPlayerCount;
        [DataMember(Name = "TotalTime")]
        public uint TotalTime;
        [DataMember(Name = "Stats")]
        public StatsUnion Stats;

        public MatchQueue(
            string Username,
            SpacetimeDB.Timestamp JoinTime,
            uint Evaluate,
            uint TargetPlayerCount,
            uint TotalTime,
            StatsUnion Stats
        )
        {
            this.Username = Username;
            this.JoinTime = JoinTime;
            this.Evaluate = Evaluate;
            this.TargetPlayerCount = TargetPlayerCount;
            this.TotalTime = TotalTime;
            this.Stats = Stats;
        }

        public MatchQueue()
        {
            this.Username = "";
            this.Stats = null!;
        }
    }
}
