// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MatchContext
    {
        [DataMember(Name = "MatchId")]
        public uint MatchId;
        [DataMember(Name = "State")]
        public MatchState State;
        [DataMember(Name = "PlayerCount")]
        public uint PlayerCount;
        [DataMember(Name = "TurnIndex")]
        public uint TurnIndex;
        [DataMember(Name = "CurrentPlayerIndex")]
        public uint CurrentPlayerIndex;
        [DataMember(Name = "CreatedAt")]
        public SpacetimeDB.Timestamp CreatedAt;

        public MatchContext(
            uint MatchId,
            MatchState State,
            uint PlayerCount,
            uint TurnIndex,
            uint CurrentPlayerIndex,
            SpacetimeDB.Timestamp CreatedAt
        )
        {
            this.MatchId = MatchId;
            this.State = State;
            this.PlayerCount = PlayerCount;
            this.TurnIndex = TurnIndex;
            this.CurrentPlayerIndex = CurrentPlayerIndex;
            this.CreatedAt = CreatedAt;
        }

        public MatchContext()
        {
        }
    }
}
