// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MatchInfo
    {
        [DataMember(Name = "Win")]
        public uint Win;
        [DataMember(Name = "Loss")]
        public uint Loss;

        public MatchInfo(
            uint Win,
            uint Loss
        )
        {
            this.Win = Win;
            this.Loss = Loss;
        }

        public MatchInfo()
        {
        }
    }
}
