// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerStats
    {
        [DataMember(Name = "MaxHealth")]
        public uint MaxHealth;
        [DataMember(Name = "CurrentHealth")]
        public uint CurrentHealth;
        [DataMember(Name = "MaxEnergy")]
        public uint MaxEnergy;
        [DataMember(Name = "CurrentEnergy")]
        public uint CurrentEnergy;

        public PlayerStats(
            uint MaxHealth,
            uint CurrentHealth,
            uint MaxEnergy,
            uint CurrentEnergy
        )
        {
            this.MaxHealth = MaxHealth;
            this.CurrentHealth = CurrentHealth;
            this.MaxEnergy = MaxEnergy;
            this.CurrentEnergy = CurrentEnergy;
        }

        public PlayerStats()
        {
        }
    }
}
