// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerTimerSchedule
    {
        [DataMember(Name = "Id")]
        public ulong Id;
        [DataMember(Name = "ScheduleAt")]
        public SpacetimeDB.ScheduleAt ScheduleAt;
        [DataMember(Name = "Username")]
        public string Username;

        public PlayerTimerSchedule(
            ulong Id,
            SpacetimeDB.ScheduleAt ScheduleAt,
            string Username
        )
        {
            this.Id = Id;
            this.ScheduleAt = ScheduleAt;
            this.Username = Username;
        }

        public PlayerTimerSchedule()
        {
            this.ScheduleAt = null!;
            this.Username = "";
        }
    }
}
