// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerBaseCardHand
    {
        [DataMember(Name = "CardInstanceId")]
        public uint CardInstanceId;
        [DataMember(Name = "BaseCardId")]
        public uint BaseCardId;
        [DataMember(Name = "MatchId")]
        public uint MatchId;
        [DataMember(Name = "Owner")]
        public string Owner;

        public PlayerBaseCardHand(
            uint CardInstanceId,
            uint BaseCardId,
            uint MatchId,
            string Owner
        )
        {
            this.CardInstanceId = CardInstanceId;
            this.BaseCardId = BaseCardId;
            this.MatchId = MatchId;
            this.Owner = Owner;
        }

        public PlayerBaseCardHand()
        {
            this.Owner = "";
        }
    }
}
