// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerContext
    {
        [DataMember(Name = "Username")]
        public string Username;
        [DataMember(Name = "MatchId")]
        public uint MatchId;
        [DataMember(Name = "Stats")]
        public StatsUnion Stats;
        [DataMember(Name = "PlayerIndex")]
        public uint PlayerIndex;
        [DataMember(Name = "IsReady")]
        public bool IsReady;
        [DataMember(Name = "TotalTime")]
        public uint TotalTime;
        [DataMember(Name = "Phase")]
        public GamePhase Phase;

        public PlayerContext(
            string Username,
            uint MatchId,
            StatsUnion Stats,
            uint PlayerIndex,
            bool IsReady,
            uint TotalTime,
            GamePhase Phase
        )
        {
            this.Username = Username;
            this.MatchId = MatchId;
            this.Stats = Stats;
            this.PlayerIndex = PlayerIndex;
            this.IsReady = IsReady;
            this.TotalTime = TotalTime;
            this.Phase = Phase;
        }

        public PlayerContext()
        {
            this.Username = "";
            this.Stats = null!;
        }
    }
}
