// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerAccount
    {
        [DataMember(Name = "Username")]
        public string Username;
        [DataMember(Name = "Nickname")]
        public string Nickname;
        [DataMember(Name = "Info")]
        public MatchInfo Info;
        [DataMember(Name = "Rank")]
        public uint Rank;
        [DataMember(Name = "Evaluate")]
        public uint Evaluate;

        public PlayerAccount(
            string Username,
            string Nickname,
            MatchInfo Info,
            uint Rank,
            uint Evaluate
        )
        {
            this.Username = Username;
            this.Nickname = Nickname;
            this.Info = Info;
            this.Rank = Rank;
            this.Evaluate = Evaluate;
        }

        public PlayerAccount()
        {
            this.Username = "";
            this.Nickname = "";
            this.Info = new();
        }
    }
}
