// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TestHero1Stats
    {
        [DataMember(Name = "BaseStats")]
        public PlayerStats BaseStats;
        [DataMember(Name = "Heal")]
        public uint Heal;

        public TestHero1Stats(
            PlayerStats BaseStats,
            uint Heal
        )
        {
            this.BaseStats = BaseStats;
            this.Heal = Heal;
        }

        public TestHero1Stats()
        {
            this.BaseStats = new();
        }
    }
}
