// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class UserProfile
    {
        [DataMember(Name = "AccountId")]
        public uint AccountId;
        [DataMember(Name = "Wins")]
        public uint Wins;
        [DataMember(Name = "Losses")]
        public uint Losses;
        [DataMember(Name = "InMatch")]
        public bool InMatch;
        [DataMember(Name = "CurrentMatchId")]
        public ulong CurrentMatchId;

        public UserProfile(
            uint AccountId,
            uint Wins,
            uint Losses,
            bool InMatch,
            ulong CurrentMatchId
        )
        {
            this.AccountId = AccountId;
            this.Wins = Wins;
            this.Losses = Losses;
            this.InMatch = InMatch;
            this.CurrentMatchId = CurrentMatchId;
        }

        public UserProfile()
        {
        }
    }
}
