// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ValidateInfo
    {
        [DataMember(Name = "ValidateInfoId")]
        public string ValidateInfoId;
        [DataMember(Name = "HashCode")]
        public string HashCode;

        public ValidateInfo(
            string ValidateInfoId,
            string HashCode
        )
        {
            this.ValidateInfoId = ValidateInfoId;
            this.HashCode = HashCode;
        }

        public ValidateInfo()
        {
            this.ValidateInfoId = "";
            this.HashCode = "";
        }
    }
}
