// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AuthLogoutHandler(ReducerEventContext ctx, string username);
        public event AuthLogoutHandler? OnAuthLogout;

        public void AuthLogout(string username)
        {
            conn.InternalCallReducer(new Reducer.AuthLogout(username), this.SetCallReducerFlags.AuthLogoutFlags);
        }

        public bool InvokeAuthLogout(ReducerEventContext ctx, Reducer.AuthLogout args)
        {
            if (OnAuthLogout == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAuthLogout(
                ctx,
                args.Username
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AuthLogout : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;

            public AuthLogout(string Username)
            {
                this.Username = Username;
            }

            public AuthLogout()
            {
                this.Username = "";
            }

            string IReducerArgs.ReducerName => "AuthLogout";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AuthLogoutFlags;
        public void AuthLogout(CallReducerFlags flags) => AuthLogoutFlags = flags;
    }
}
