// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AuthRegisterHandler(ReducerEventContext ctx, string username, string password);
        public event AuthRegisterHandler? OnAuthRegister;

        public void AuthRegister(string username, string password)
        {
            conn.InternalCallReducer(new Reducer.AuthRegister(username, password), this.SetCallReducerFlags.AuthRegisterFlags);
        }

        public bool InvokeAuthRegister(ReducerEventContext ctx, Reducer.AuthRegister args)
        {
            if (OnAuthRegister == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAuthRegister(
                ctx,
                args.Username,
                args.Password
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AuthRegister : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "password")]
            public string Password;

            public AuthRegister(
                string Username,
                string Password
            )
            {
                this.Username = Username;
                this.Password = Password;
            }

            public AuthRegister()
            {
                this.Username = "";
                this.Password = "";
            }

            string IReducerArgs.ReducerName => "AuthRegister";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AuthRegisterFlags;
        public void AuthRegister(CallReducerFlags flags) => AuthRegisterFlags = flags;
    }
}
