// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AuthLoginHandler(ReducerEventContext ctx, string username, string password);
        public event AuthLoginHandler? OnAuthLogin;

        public void AuthLogin(string username, string password)
        {
            conn.InternalCallReducer(new Reducer.AuthLogin(username, password), this.SetCallReducerFlags.AuthLoginFlags);
        }

        public bool InvokeAuthLogin(ReducerEventContext ctx, Reducer.AuthLogin args)
        {
            if (OnAuthLogin == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAuthLogin(
                ctx,
                args.Username,
                args.Password
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AuthLogin : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "password")]
            public string Password;

            public AuthLogin(
                string Username,
                string Password
            )
            {
                this.Username = Username;
                this.Password = Password;
            }

            public AuthLogin()
            {
                this.Username = "";
                this.Password = "";
            }

            string IReducerArgs.ReducerName => "AuthLogin";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AuthLoginFlags;
        public void AuthLogin(CallReducerFlags flags) => AuthLoginFlags = flags;
    }
}
