// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CancelMatchHandler(ReducerEventContext ctx, string username);
        public event CancelMatchHandler? OnCancelMatch;

        public void CancelMatch(string username)
        {
            conn.InternalCallReducer(new Reducer.CancelMatch(username), this.SetCallReducerFlags.CancelMatchFlags);
        }

        public bool InvokeCancelMatch(ReducerEventContext ctx, Reducer.CancelMatch args)
        {
            if (OnCancelMatch == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCancelMatch(
                ctx,
                args.Username
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CancelMatch : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;

            public CancelMatch(string Username)
            {
                this.Username = Username;
            }

            public CancelMatch()
            {
                this.Username = "";
            }

            string IReducerArgs.ReducerName => "CancelMatch";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CancelMatchFlags;
        public void CancelMatch(CallReducerFlags flags) => CancelMatchFlags = flags;
    }
}
