// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InitializeHandler(ReducerEventContext ctx, string username, string nickname);
        public event InitializeHandler? OnInitialize;

        public void Initialize(string username, string nickname)
        {
            conn.InternalCallReducer(new Reducer.Initialize(username, nickname), this.SetCallReducerFlags.InitializeFlags);
        }

        public bool InvokeInitialize(ReducerEventContext ctx, Reducer.Initialize args)
        {
            if (OnInitialize == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInitialize(
                ctx,
                args.Username,
                args.Nickname
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Initialize : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "nickname")]
            public string Nickname;

            public Initialize(
                string Username,
                string Nickname
            )
            {
                this.Username = Username;
                this.Nickname = Nickname;
            }

            public Initialize()
            {
                this.Username = "";
                this.Nickname = "";
            }

            string IReducerArgs.ReducerName => "Initialize";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags InitializeFlags;
        public void Initialize(CallReducerFlags flags) => InitializeFlags = flags;
    }
}
