// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InitializePlayerContextHandler(ReducerEventContext ctx, string username, StatsUnion stats);
        public event InitializePlayerContextHandler? OnInitializePlayerContext;

        public void InitializePlayerContext(string username, StatsUnion stats)
        {
            conn.InternalCallReducer(new Reducer.InitializePlayerContext(username, stats), this.SetCallReducerFlags.InitializePlayerContextFlags);
        }

        public bool InvokeInitializePlayerContext(ReducerEventContext ctx, Reducer.InitializePlayerContext args)
        {
            if (OnInitializePlayerContext == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInitializePlayerContext(
                ctx,
                args.Username,
                args.Stats
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InitializePlayerContext : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "stats")]
            public StatsUnion Stats;

            public InitializePlayerContext(
                string Username,
                StatsUnion Stats
            )
            {
                this.Username = Username;
                this.Stats = Stats;
            }

            public InitializePlayerContext()
            {
                this.Username = "";
                this.Stats = null!;
            }

            string IReducerArgs.ReducerName => "InitializePlayerContext";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags InitializePlayerContextFlags;
        public void InitializePlayerContext(CallReducerFlags flags) => InitializePlayerContextFlags = flags;
    }
}
