// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerTimerHandler(ReducerEventContext ctx, PlayerTimerSchedule schedule);
        public event PlayerTimerHandler? OnPlayerTimer;

        public void PlayerTimer(PlayerTimerSchedule schedule)
        {
            conn.InternalCallReducer(new Reducer.PlayerTimer(schedule), this.SetCallReducerFlags.PlayerTimerFlags);
        }

        public bool InvokePlayerTimer(ReducerEventContext ctx, Reducer.PlayerTimer args)
        {
            if (OnPlayerTimer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerTimer(
                ctx,
                args.Schedule
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerTimer : Reducer, IReducerArgs
        {
            [DataMember(Name = "schedule")]
            public PlayerTimerSchedule Schedule;

            public PlayerTimer(PlayerTimerSchedule Schedule)
            {
                this.Schedule = Schedule;
            }

            public PlayerTimer()
            {
                this.Schedule = new();
            }

            string IReducerArgs.ReducerName => "PlayerTimer";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerTimerFlags;
        public void PlayerTimer(CallReducerFlags flags) => PlayerTimerFlags = flags;
    }
}
