// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerRenameHandler(ReducerEventContext ctx, string nickname);
        public event PlayerRenameHandler? OnPlayerRename;

        public void PlayerRename(string nickname)
        {
            conn.InternalCallReducer(new Reducer.PlayerRename(nickname), this.SetCallReducerFlags.PlayerRenameFlags);
        }

        public bool InvokePlayerRename(ReducerEventContext ctx, Reducer.PlayerRename args)
        {
            if (OnPlayerRename == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerRename(
                ctx,
                args.Nickname
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerRename : Reducer, IReducerArgs
        {
            [DataMember(Name = "nickname")]
            public string Nickname;

            public PlayerRename(string Nickname)
            {
                this.Nickname = Nickname;
            }

            public PlayerRename()
            {
                this.Nickname = "";
            }

            string IReducerArgs.ReducerName => "PlayerRename";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerRenameFlags;
        public void PlayerRename(CallReducerFlags flags) => PlayerRenameFlags = flags;
    }
}
