// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerReadyHandler(ReducerEventContext ctx, string username);
        public event PlayerReadyHandler? OnPlayerReady;

        public void PlayerReady(string username)
        {
            conn.InternalCallReducer(new Reducer.PlayerReady(username), this.SetCallReducerFlags.PlayerReadyFlags);
        }

        public bool InvokePlayerReady(ReducerEventContext ctx, Reducer.PlayerReady args)
        {
            if (OnPlayerReady == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerReady(
                ctx,
                args.Username
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerReady : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;

            public PlayerReady(string Username)
            {
                this.Username = Username;
            }

            public PlayerReady()
            {
                this.Username = "";
            }

            string IReducerArgs.ReducerName => "PlayerReady";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerReadyFlags;
        public void PlayerReady(CallReducerFlags flags) => PlayerReadyFlags = flags;
    }
}
