// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RequestDealCardHandler(ReducerEventContext ctx, string username, uint count);
        public event RequestDealCardHandler? OnRequestDealCard;

        public void RequestDealCard(string username, uint count)
        {
            conn.InternalCallReducer(new Reducer.RequestDealCard(username, count), this.SetCallReducerFlags.RequestDealCardFlags);
        }

        public bool InvokeRequestDealCard(ReducerEventContext ctx, Reducer.RequestDealCard args)
        {
            if (OnRequestDealCard == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRequestDealCard(
                ctx,
                args.Username,
                args.Count
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RequestDealCard : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "count")]
            public uint Count;

            public RequestDealCard(
                string Username,
                uint Count
            )
            {
                this.Username = Username;
                this.Count = Count;
            }

            public RequestDealCard()
            {
                this.Username = "";
            }

            string IReducerArgs.ReducerName => "RequestDealCard";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RequestDealCardFlags;
        public void RequestDealCard(CallReducerFlags flags) => RequestDealCardFlags = flags;
    }
}
