// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SwitchTimeHandler(ReducerEventContext ctx, string username, uint next);
        public event SwitchTimeHandler? OnSwitchTime;

        public void SwitchTime(string username, uint next)
        {
            conn.InternalCallReducer(new Reducer.SwitchTime(username, next), this.SetCallReducerFlags.SwitchTimeFlags);
        }

        public bool InvokeSwitchTime(ReducerEventContext ctx, Reducer.SwitchTime args)
        {
            if (OnSwitchTime == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSwitchTime(
                ctx,
                args.Username,
                args.Next
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SwitchTime : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "next")]
            public uint Next;

            public SwitchTime(
                string Username,
                uint Next
            )
            {
                this.Username = Username;
                this.Next = Next;
            }

            public SwitchTime()
            {
                this.Username = "";
            }

            string IReducerArgs.ReducerName => "SwitchTime";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SwitchTimeFlags;
        public void SwitchTime(CallReducerFlags flags) => SwitchTimeFlags = flags;
    }
}
