// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryEnqueuePlayerHandler(ReducerEventContext ctx, string username, StatsUnion stats, uint targetPlayerCount, uint totalTime);
        public event TryEnqueuePlayerHandler? OnTryEnqueuePlayer;

        public void TryEnqueuePlayer(string username, StatsUnion stats, uint targetPlayerCount, uint totalTime)
        {
            conn.InternalCallReducer(new Reducer.TryEnqueuePlayer(username, stats, targetPlayerCount, totalTime), this.SetCallReducerFlags.TryEnqueuePlayerFlags);
        }

        public bool InvokeTryEnqueuePlayer(ReducerEventContext ctx, Reducer.TryEnqueuePlayer args)
        {
            if (OnTryEnqueuePlayer == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryEnqueuePlayer(
                ctx,
                args.Username,
                args.Stats,
                args.TargetPlayerCount,
                args.TotalTime
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryEnqueuePlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "username")]
            public string Username;
            [DataMember(Name = "stats")]
            public StatsUnion Stats;
            [DataMember(Name = "targetPlayerCount")]
            public uint TargetPlayerCount;
            [DataMember(Name = "totalTime")]
            public uint TotalTime;

            public TryEnqueuePlayer(
                string Username,
                StatsUnion Stats,
                uint TargetPlayerCount,
                uint TotalTime
            )
            {
                this.Username = Username;
                this.Stats = Stats;
                this.TargetPlayerCount = TargetPlayerCount;
                this.TotalTime = TotalTime;
            }

            public TryEnqueuePlayer()
            {
                this.Username = "";
                this.Stats = null!;
            }

            string IReducerArgs.ReducerName => "TryEnqueuePlayer";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryEnqueuePlayerFlags;
        public void TryEnqueuePlayer(CallReducerFlags flags) => TryEnqueuePlayerFlags = flags;
    }
}
