// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TryValidateHeroCardHandler(ReducerEventContext ctx, System.Collections.Generic.List<HeroCard> cards);
        public event TryValidateHeroCardHandler? OnTryValidateHeroCard;

        public void TryValidateHeroCard(System.Collections.Generic.List<HeroCard> cards)
        {
            conn.InternalCallReducer(new Reducer.TryValidateHeroCard(cards), this.SetCallReducerFlags.TryValidateHeroCardFlags);
        }

        public bool InvokeTryValidateHeroCard(ReducerEventContext ctx, Reducer.TryValidateHeroCard args)
        {
            if (OnTryValidateHeroCard == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTryValidateHeroCard(
                ctx,
                args.Cards
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TryValidateHeroCard : Reducer, IReducerArgs
        {
            [DataMember(Name = "cards")]
            public System.Collections.Generic.List<HeroCard> Cards;

            public TryValidateHeroCard(System.Collections.Generic.List<HeroCard> Cards)
            {
                this.Cards = Cards;
            }

            public TryValidateHeroCard()
            {
                this.Cards = new();
            }

            string IReducerArgs.ReducerName => "TryValidateHeroCard";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TryValidateHeroCardFlags;
        public void TryValidateHeroCard(CallReducerFlags flags) => TryValidateHeroCardFlags = flags;
    }
}
