// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void VerifyDataHandler(ReducerEventContext ctx, string target, string playLoad);
        public event VerifyDataHandler? OnVerifyData;

        public void VerifyData(string target, string playLoad)
        {
            conn.InternalCallReducer(new Reducer.VerifyData(target, playLoad), this.SetCallReducerFlags.VerifyDataFlags);
        }

        public bool InvokeVerifyData(ReducerEventContext ctx, Reducer.VerifyData args)
        {
            if (OnVerifyData == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnVerifyData(
                ctx,
                args.Target,
                args.PlayLoad
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class VerifyData : Reducer, IReducerArgs
        {
            [DataMember(Name = "target")]
            public string Target;
            [DataMember(Name = "play_load")]
            public string PlayLoad;

            public VerifyData(
                string Target,
                string PlayLoad
            )
            {
                this.Target = Target;
                this.PlayLoad = PlayLoad;
            }

            public VerifyData()
            {
                this.Target = "";
                this.PlayLoad = "";
            }

            string IReducerArgs.ReducerName => "VerifyData";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags VerifyDataFlags;
        public void VerifyData(CallReducerFlags flags) => VerifyDataFlags = flags;
    }
}
